### ISSUE TITLE
cocoapod install libwebp error

### ISSUE THREAD

**Issue by wankang189** [dulingkang/SSCycleScrollView#1]
[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/k4/69nzkys54rz3w5lbddk42qbc0000gn/T/d20161019-8898-1arba4h --template= --single-branch --depth 1 --branch v0.5.1

Cloning into '/var/folders/k4/69nzkys54rz3w5lbddk42qbc0000gn/T/d20161019-8898-1arba4h'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by dulingkang** [comment]
webp下载需要改host或者连vpn，[改host地址 https://github.com/dulingkang/host](https://github.com/dulingkang/host)
